services:

  redis:
    image: 'redis:alpine'
    env_file:
      - './dev/settings.env'

  postgres:
    image: "postgres:12"
    #command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    env_file:
      - './dev/settings.env'
    volumes:
      - "pg_data:/var/lib/postgresql/data"

  minio:
    image: minio/minio
    command: "server /var/lib/minio"
    volumes:
      - 'minio:/var/lib/minio'
    env_file:
      - './dev/settings.env'
    networks:
      default:
        aliases:
          - pulp3.minio
 
  goapi:
    build: .
    ports:
      - '8080:8080'
    command: "/bin/bash -c 'cd /src; go run api/api.go'"
    env_file:
      - './dev/settings.env'
    volumes:
      - './src:/src'
      - './dev/galaxy_ng/bin:/opt/bin'
      - "pulp:/var/lib/pulp"
    depends_on:
      - postgres
      - minio
      - galaxyapi

  galaxyapi:
    build: ./dev/galaxy_ng/
    command: '/opt/bin/start-api'
    ports:
      - "5001:8000" 
    env_file:
      - './dev/settings.env'
    volumes:
      - './dev/galaxy_ng/bin:/opt/bin'
      - './dev/certs:/etc/pulp/certs'
      - "pulp:/var/lib/pulp"
    depends_on:
      - minio
      - postgres
      - redis

  pulpcontent:
    build: ./dev/galaxy_ng/
    command: '/opt/bin/start-content'
    ports:
      - "24816:24816"
    env_file:
      - './dev/settings.env'
    volumes:
      - './dev/galaxy_ng/bin:/opt/bin'
      - './dev/certs:/etc/pulp/certs'
      - "pulp:/var/lib/pulp"
    depends_on:
      - ansible

  pulpworker:
    build: ./dev/galaxy_ng/
    command: '/opt/bin/start-worker'
    env_file:
      - './dev/settings.env'
    volumes:
      - './dev/galaxy_ng/bin:/opt/bin'
      - './dev/certs:/etc/pulp/certs'
      - "pulp:/var/lib/pulp"
    depends_on:
      - ansible

  ansible:
    build: ./dev/playbooks
    command: /bin/bash -c 'cd /playbooks; ANSIBLE_STDOUT_CALLBACK=community.general.yaml ansible-playbook -v -i "localhost," -v stack.yml'
    env_file:
      - './dev/settings.env'
    volumes:
      - './dev/playbooks:/playbooks'
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - minio
      - postgres
      - redis
      - galaxyapi

volumes:
  pulp:
    name: gng_pulp
  minio:
    name: gng_minio
  pg_data:
    name: gng_pg_data
  #redis_data:
  #  name: redis_data
